/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LineupIndexRouteImport } from './routes/lineup/index'
import { Route as LineupBandIdRouteImport } from './routes/lineup/$bandId'
import { Route as TicketsTicketsRouteImport } from './routes/_tickets/tickets'
import { Route as ImpressumImpressumRouteImport } from './routes/_impressum/impressum'
import { Route as CalendarCalendarRouteImport } from './routes/_calendar/calendar'
import { Route as AboutAboutRouteImport } from './routes/_about/about'
import { Route as SignUpSignUpSplatRouteImport } from './routes/_sign-up/sign-up.$'
import { Route as SignInSignInSplatRouteImport } from './routes/_sign-in/sign-in.$'
import { Route as AuthenticatedDashboardDashboardRouteImport } from './routes/_authenticated/_dashboard/dashboard'
import { Route as AuthenticatedDashboardBandsNewRouteImport } from './routes/_authenticated/_dashboard/_bands/new'
import { Route as AuthenticatedDashboardBandsBandsRouteImport } from './routes/_authenticated/_dashboard/_bands/bands'
import { Route as AuthenticatedDashboardBandsBandIdRouteImport } from './routes/_authenticated/_dashboard/_bands/$bandId'
import { Route as AuthenticatedDashboardBandsBandIdEditRouteImport } from './routes/_authenticated/_dashboard/_bands/$bandId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LineupIndexRoute = LineupIndexRouteImport.update({
  id: '/lineup/',
  path: '/lineup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LineupBandIdRoute = LineupBandIdRouteImport.update({
  id: '/lineup/$bandId',
  path: '/lineup/$bandId',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketsRoute = TicketsTicketsRouteImport.update({
  id: '/_tickets/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumImpressumRoute = ImpressumImpressumRouteImport.update({
  id: '/_impressum/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarCalendarRoute = CalendarCalendarRouteImport.update({
  id: '/_calendar/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAboutRoute = AboutAboutRouteImport.update({
  id: '/_about/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSignUpSplatRoute = SignUpSignUpSplatRouteImport.update({
  id: '/_sign-up/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSignInSplatRoute = SignInSignInSplatRouteImport.update({
  id: '/_sign-in/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardDashboardRoute =
  AuthenticatedDashboardDashboardRouteImport.update({
    id: '/_dashboard/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBandsNewRoute =
  AuthenticatedDashboardBandsNewRouteImport.update({
    id: '/_dashboard/_bands/new',
    path: '/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBandsBandsRoute =
  AuthenticatedDashboardBandsBandsRouteImport.update({
    id: '/_dashboard/_bands/bands',
    path: '/bands',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBandsBandIdRoute =
  AuthenticatedDashboardBandsBandIdRouteImport.update({
    id: '/_dashboard/_bands/$bandId',
    path: '/$bandId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardBandsBandIdEditRoute =
  AuthenticatedDashboardBandsBandIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedDashboardBandsBandIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutAboutRoute
  '/calendar': typeof CalendarCalendarRoute
  '/impressum': typeof ImpressumImpressumRoute
  '/tickets': typeof TicketsTicketsRoute
  '/lineup/$bandId': typeof LineupBandIdRoute
  '/lineup/': typeof LineupIndexRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/sign-in/$': typeof SignInSignInSplatRoute
  '/sign-up/$': typeof SignUpSignUpSplatRoute
  '/$bandId': typeof AuthenticatedDashboardBandsBandIdRouteWithChildren
  '/bands': typeof AuthenticatedDashboardBandsBandsRoute
  '/new': typeof AuthenticatedDashboardBandsNewRoute
  '/$bandId/edit': typeof AuthenticatedDashboardBandsBandIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutAboutRoute
  '/calendar': typeof CalendarCalendarRoute
  '/impressum': typeof ImpressumImpressumRoute
  '/tickets': typeof TicketsTicketsRoute
  '/lineup/$bandId': typeof LineupBandIdRoute
  '/lineup': typeof LineupIndexRoute
  '/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/sign-in/$': typeof SignInSignInSplatRoute
  '/sign-up/$': typeof SignUpSignUpSplatRoute
  '/$bandId': typeof AuthenticatedDashboardBandsBandIdRouteWithChildren
  '/bands': typeof AuthenticatedDashboardBandsBandsRoute
  '/new': typeof AuthenticatedDashboardBandsNewRoute
  '/$bandId/edit': typeof AuthenticatedDashboardBandsBandIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_about/about': typeof AboutAboutRoute
  '/_calendar/calendar': typeof CalendarCalendarRoute
  '/_impressum/impressum': typeof ImpressumImpressumRoute
  '/_tickets/tickets': typeof TicketsTicketsRoute
  '/lineup/$bandId': typeof LineupBandIdRoute
  '/lineup/': typeof LineupIndexRoute
  '/_authenticated/_dashboard/dashboard': typeof AuthenticatedDashboardDashboardRoute
  '/_sign-in/sign-in/$': typeof SignInSignInSplatRoute
  '/_sign-up/sign-up/$': typeof SignUpSignUpSplatRoute
  '/_authenticated/_dashboard/_bands/$bandId': typeof AuthenticatedDashboardBandsBandIdRouteWithChildren
  '/_authenticated/_dashboard/_bands/bands': typeof AuthenticatedDashboardBandsBandsRoute
  '/_authenticated/_dashboard/_bands/new': typeof AuthenticatedDashboardBandsNewRoute
  '/_authenticated/_dashboard/_bands/$bandId/edit': typeof AuthenticatedDashboardBandsBandIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/calendar'
    | '/impressum'
    | '/tickets'
    | '/lineup/$bandId'
    | '/lineup/'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$bandId'
    | '/bands'
    | '/new'
    | '/$bandId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/impressum'
    | '/tickets'
    | '/lineup/$bandId'
    | '/lineup'
    | '/dashboard'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/$bandId'
    | '/bands'
    | '/new'
    | '/$bandId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_about/about'
    | '/_calendar/calendar'
    | '/_impressum/impressum'
    | '/_tickets/tickets'
    | '/lineup/$bandId'
    | '/lineup/'
    | '/_authenticated/_dashboard/dashboard'
    | '/_sign-in/sign-in/$'
    | '/_sign-up/sign-up/$'
    | '/_authenticated/_dashboard/_bands/$bandId'
    | '/_authenticated/_dashboard/_bands/bands'
    | '/_authenticated/_dashboard/_bands/new'
    | '/_authenticated/_dashboard/_bands/$bandId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutAboutRoute: typeof AboutAboutRoute
  CalendarCalendarRoute: typeof CalendarCalendarRoute
  ImpressumImpressumRoute: typeof ImpressumImpressumRoute
  TicketsTicketsRoute: typeof TicketsTicketsRoute
  LineupBandIdRoute: typeof LineupBandIdRoute
  LineupIndexRoute: typeof LineupIndexRoute
  SignInSignInSplatRoute: typeof SignInSignInSplatRoute
  SignUpSignUpSplatRoute: typeof SignUpSignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineup/': {
      id: '/lineup/'
      path: '/lineup'
      fullPath: '/lineup/'
      preLoaderRoute: typeof LineupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineup/$bandId': {
      id: '/lineup/$bandId'
      path: '/lineup/$bandId'
      fullPath: '/lineup/$bandId'
      preLoaderRoute: typeof LineupBandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tickets/tickets': {
      id: '/_tickets/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_impressum/impressum': {
      id: '/_impressum/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_calendar/calendar': {
      id: '/_calendar/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_about/about': {
      id: '/_about/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sign-up/sign-up/$': {
      id: '/_sign-up/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sign-in/sign-in/$': {
      id: '/_sign-in/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/dashboard': {
      id: '/_authenticated/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/_bands/new': {
      id: '/_authenticated/_dashboard/_bands/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedDashboardBandsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/_bands/bands': {
      id: '/_authenticated/_dashboard/_bands/bands'
      path: '/bands'
      fullPath: '/bands'
      preLoaderRoute: typeof AuthenticatedDashboardBandsBandsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/_bands/$bandId': {
      id: '/_authenticated/_dashboard/_bands/$bandId'
      path: '/$bandId'
      fullPath: '/$bandId'
      preLoaderRoute: typeof AuthenticatedDashboardBandsBandIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_dashboard/_bands/$bandId/edit': {
      id: '/_authenticated/_dashboard/_bands/$bandId/edit'
      path: '/edit'
      fullPath: '/$bandId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardBandsBandIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardBandsBandIdRoute
    }
  }
}

interface AuthenticatedDashboardBandsBandIdRouteChildren {
  AuthenticatedDashboardBandsBandIdEditRoute: typeof AuthenticatedDashboardBandsBandIdEditRoute
}

const AuthenticatedDashboardBandsBandIdRouteChildren: AuthenticatedDashboardBandsBandIdRouteChildren =
  {
    AuthenticatedDashboardBandsBandIdEditRoute:
      AuthenticatedDashboardBandsBandIdEditRoute,
  }

const AuthenticatedDashboardBandsBandIdRouteWithChildren =
  AuthenticatedDashboardBandsBandIdRoute._addFileChildren(
    AuthenticatedDashboardBandsBandIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardDashboardRoute: typeof AuthenticatedDashboardDashboardRoute
  AuthenticatedDashboardBandsBandIdRoute: typeof AuthenticatedDashboardBandsBandIdRouteWithChildren
  AuthenticatedDashboardBandsBandsRoute: typeof AuthenticatedDashboardBandsBandsRoute
  AuthenticatedDashboardBandsNewRoute: typeof AuthenticatedDashboardBandsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardDashboardRoute: AuthenticatedDashboardDashboardRoute,
  AuthenticatedDashboardBandsBandIdRoute:
    AuthenticatedDashboardBandsBandIdRouteWithChildren,
  AuthenticatedDashboardBandsBandsRoute: AuthenticatedDashboardBandsBandsRoute,
  AuthenticatedDashboardBandsNewRoute: AuthenticatedDashboardBandsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutAboutRoute: AboutAboutRoute,
  CalendarCalendarRoute: CalendarCalendarRoute,
  ImpressumImpressumRoute: ImpressumImpressumRoute,
  TicketsTicketsRoute: TicketsTicketsRoute,
  LineupBandIdRoute: LineupBandIdRoute,
  LineupIndexRoute: LineupIndexRoute,
  SignInSignInSplatRoute: SignInSignInSplatRoute,
  SignUpSignUpSplatRoute: SignUpSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
