/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesRulesRouteImport } from './routes/_rules/rules'
import { Route as ImpressumImpressumRouteImport } from './routes/_impressum/impressum'
import { Route as HistoryHistoryRouteImport } from './routes/_history/history'
import { Route as GameGameRouteImport } from './routes/_game/game'
import { Route as AboutAboutRouteImport } from './routes/_about/about'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRulesRoute = RulesRulesRouteImport.update({
  id: '/_rules/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumImpressumRoute = ImpressumImpressumRouteImport.update({
  id: '/_impressum/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryHistoryRoute = HistoryHistoryRouteImport.update({
  id: '/_history/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameRoute = GameGameRouteImport.update({
  id: '/_game/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAboutRoute = AboutAboutRouteImport.update({
  id: '/_about/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutAboutRoute
  '/game': typeof GameGameRoute
  '/history': typeof HistoryHistoryRoute
  '/impressum': typeof ImpressumImpressumRoute
  '/rules': typeof RulesRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutAboutRoute
  '/game': typeof GameGameRoute
  '/history': typeof HistoryHistoryRoute
  '/impressum': typeof ImpressumImpressumRoute
  '/rules': typeof RulesRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_about/about': typeof AboutAboutRoute
  '/_game/game': typeof GameGameRoute
  '/_history/history': typeof HistoryHistoryRoute
  '/_impressum/impressum': typeof ImpressumImpressumRoute
  '/_rules/rules': typeof RulesRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/game' | '/history' | '/impressum' | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/game' | '/history' | '/impressum' | '/rules'
  id:
    | '__root__'
    | '/'
    | '/_about/about'
    | '/_game/game'
    | '/_history/history'
    | '/_impressum/impressum'
    | '/_rules/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutAboutRoute: typeof AboutAboutRoute
  GameGameRoute: typeof GameGameRoute
  HistoryHistoryRoute: typeof HistoryHistoryRoute
  ImpressumImpressumRoute: typeof ImpressumImpressumRoute
  RulesRulesRoute: typeof RulesRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_rules/rules': {
      id: '/_rules/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_impressum/impressum': {
      id: '/_impressum/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_history/history': {
      id: '/_history/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_game/game': {
      id: '/_game/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_about/about': {
      id: '/_about/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutAboutRoute: AboutAboutRoute,
  GameGameRoute: GameGameRoute,
  HistoryHistoryRoute: HistoryHistoryRoute,
  ImpressumImpressumRoute: ImpressumImpressumRoute,
  RulesRulesRoute: RulesRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
